const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const labelMap={networking:'Networking',security:'Security & IAM',serverless:'Serverless & APIs',databases:'Databases',linux:'Linux & Systems',monitoring:'Monitoring',cloud:'Cloud Foundations'};
function tags(p,n=5){return p.technologies.slice(0,n).map(t=>`<span class="tag">${t}</span>`).join('')}
function card(p,featured=false){return `<article class="${featured?'feature-card':'project-card'}" data-category="${p.category}"><div class="card-top"><div class="icon">${p.icon}</div><div class="num">${p.number}</div></div><div class="category">${labelMap[p.category]||p.category}</div><h3>${p.title}</h3><p>${p.description}</p><div class="tags">${tags(p)}</div><a class="case-link" href="projects.html?p=${p.slug}">View case study →</a></article>`}
function renderHome(){const f=$('#featured-projects'),g=$('#project-grid');if(!f||!g)return;f.innerHTML=PROJECTS.filter(p=>p.featured).map(p=>card(p,true)).join('');g.innerHTML=PROJECTS.map(p=>card(p)).join('');$$('.filter').forEach(b=>b.addEventListener('click',()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');const c=b.dataset.filter;$$('.project-card').forEach(x=>x.classList.toggle('hidden',c!=='all'&&x.dataset.category!==c))}))}
function architecture(p){if(!p.architecture)return '';return `<div class="architecture"><div class="label">Architecture / workflow</div><div class="arch-flow">${p.architecture.map((x,i)=>`<span class="arch-node">${x}</span>${i<p.architecture.length-1?'<span class="arch-arrow">→</span>':''}`).join('')}</div></div>`}
function implementation(p){if(!p.implementation)return '';return `<div class="case-section"><div class="label">Implementation</div><ul>${p.implementation.map(x=>`<li>${x}</li>`).join('')}</ul></div>`}
function drawCase(p,view){history.replaceState(null,'',`?p=${p.slug}`);$$('.side-filter').forEach(x=>x.classList.toggle('active',x.dataset.id===p.slug));const rich=p.featured&&p.objective;view.innerHTML=`<div class="case-hero"><div class="eyebrow">Project ${p.number} · ${labelMap[p.category]}</div><h1>${p.title}</h1><p class="section-intro">${p.description}</p><div class="tags">${tags(p,10)}</div>${rich?`<div class="case-objective"><div class="label">Objective</div><p>${p.objective}</p></div>${architecture(p)}<div class="case-detail-grid"><div class="case-section"><div class="label">Challenge / troubleshooting</div><p>${p.challenge}</p></div><div class="case-section"><div class="label">Result</div><p>${p.result}</p></div></div>${implementation(p)}<div class="case-section learned"><div class="label">What I learned</div><p>${p.learned}</p></div>`:`<div class="case-cols"><div class="case-box"><div class="label">Challenge / troubleshooting</div><p>${p.challenge}</p></div><div class="case-box"><div class="label">Result</div><p>${p.result}</p></div></div>`}</div><div class="docbar"><span>Original project documentation</span><div class="doc-actions"><a class="btn" target="_blank" href="${p.pdf}">Open PDF ↗</a></div></div><div class="docframe"><iframe title="${p.title} documentation" src="${p.pdf}"></iframe></div>`}
function renderProjects(){const list=$('#project-list'),view=$('#project-view');if(!list||!view)return;const params=new URLSearchParams(location.search);let active=params.get('p')||'p16';list.innerHTML=PROJECTS.map(p=>`<button class="side-filter" data-id="${p.slug}"><span>${p.number} · ${p.title}</span>${p.featured?'<small>Flagship</small>':''}</button>`).join('');$$('.side-filter').forEach(b=>b.addEventListener('click',()=>drawCase(PROJECTS.find(p=>p.slug===b.dataset.id),view)));drawCase(PROJECTS.find(p=>p.slug===active)||PROJECTS[0],view)}
document.addEventListener('DOMContentLoaded',()=>{renderHome();renderProjects();});
